### ISSUE TITLE
extracting id_rsa extraction problem

### ISSUE THREAD

**Issue by danielraq** [jenkinsci/hashicorp-vault-plugin#135]
Hi 
When i extract from vault ssh at Jcasc step i get '\n' marks instead of new line in my ssh key. This couse a problem becouse jenkins throws 'invalid format' exception. Any idea how to by pass this? 

```
credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            scope: GLOBAL
            id: ${USER}-ssh_key
            username: ${USER}
            passphrase: ""
            description: "SSH ${USER}"
            privateKeySource:
              directEntry:
                privateKey: `"${secret/jenkins/id_rsa}"

```
