### ISSUE TITLE
JCasC: vaultKubernetesCredential mount path

### ISSUE THREAD

**Issue by jr200** [jenkinsci/hashicorp-vault-plugin#177]
### Feature Request

I am configuring a domain-credential of type `vaultKubernetesCredential` using this JCasC snippet.

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - vaultKubernetesCredential:
          description: "vault-jenkins-k8s"
          id: "vault-jenkins-k8s"
          role: "jenkins-agent-role"
          scope: GLOBAL
```

Could I request an extension to the above that allows setting the kubernetes-auth mount-path. I think currently the only way to achieve this is post-install via the UI.

**Comment by tsurankov** [comment]
Hi @jr200,
You actually can specify mount-path as **mountPath**. 
```
      vault: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - vaultKubernetesCredential:
                  description: "Vault integration"
                  id: "vault-kubernetes-auth"
                  mountPath: "cluster-name"
                  role: "jenkins-kubernetes"
                  scope: GLOBAL
```
