### ISSUE TITLE
Support for AWS Credentials

### ISSUE THREAD

**Issue by dzieciou** [jenkinsci/hashicorp-vault-plugin#194]
### Dependencies

None

### Feature Request

I am currently migrating all our credentials from Jenkins to Vault. Unfortunatetly, current version of the plugin does not support populating Jenkins AWS Credentials.

![image](https://user-images.githubusercontent.com/7452788/137894697-4364be1d-f2f6-43e8-b052-7a3c368519db.png)

Is there any PR on that?

**Comment by dhs-rec** [comment]
Yeah, there's `Vault AWS IAM Credential`, but this seems to be something completely different...

**Comment by mifitous** [comment]
+1

**Comment by jonbrohauge** [comment]
With a combination of Vault, Jenkins Configuration-as-Code, it's possible.
If you start your Jenkins with these Environment Variables properly configured, it'll load secrets from Vault into Environment Variables:
```
CASC_VAULT_TOKEN="<TOKEN>"
CASC_VAULT_ENGINE_VERSION=<Engine version 1 or 2
CASC_VAULT_PATHS=<path/to/jenkins-secrets"
CASC_VAULT_URL=<URL to Vault>
```
Official docs on the matter: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/VAULT.md

```
---
credentials:
  system:
    domainCredentials:
      - credentials:
          - aws:
              scope: GLOBAL
              id: "AWS"
              accessKey: "${AWS_ACCESS_KEY_ID}"
              secretKey: "${AWS_SECRET_ACCESS_KEY}"
              description: "AWS Credentials"

```
